# Generated by Django 5.2.14 on 2026-05-10 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food & Dining'), ('adventure', 'Adventure'), ('culture', 'Culture & Arts'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation & Spa'), ('transport', 'Transport'), ('accommodation', 'Accommodation')], max_length=50)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('is_popular', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='cities.city')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
