# Generated by Django 5.2.14 on 2026-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='activity',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
