# Generated by Django 5.2.14 on 2026-05-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cost_index', models.DecimalField(decimal_places=2, default=1.0, help_text='Average daily cost in USD', max_digits=5)),
                ('popularity_score', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cities/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['-popularity_score'],
            },
        ),
    ]
