# Generated by Django 5.2.14 on 2026-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='city',
            name='popularity_rating',
            field=models.IntegerField(default=0),
        ),
    ]
