# Generated by Django 5.2.14 on 2026-05-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyNote',
            fields=[
            ],
            options={
                'verbose_name': 'Journey note',
                'verbose_name_plural': 'Journey notes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('trips.tripnote',),
        ),
    ]
